# **NUMPY - numerical python**

Numpy - numerical python

advantage of numpy arrays:
1. Allows several Mathematical operations
2. Faster operations

In [2]:
import numpy as np

In [3]:
#list vs numpy - time taken
from time import process_time

In [4]:
# we are calculating the time taken for adding all the elements with 5 in list datatype
list1 = [i for i in range(100000)]

start_time = process_time()
list1 = [i+5 for i in list1]
end_time = process_time()
print(end_time - start_time)

0.01403184500000032


In [5]:
#time taken by numpy array
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array = [i+5 for i in np_array]
end_time = process_time()
print(end_time - start_time)

0.004268111000000019


In [6]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([ (1,2,3,4) , (5,6,7,8) ])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array( [ (1,2,3,4), (5,6,7,8) ],dtype = float )
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays

In [13]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.26710954 0.93163303 0.41377981 0.76208436]
 [0.64252889 0.56539152 0.57063145 0.67787136]
 [0.37685101 0.0645914  0.02097198 0.3035793 ]]


In [18]:
#random integrer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[84 90 19 16 81]
 [69 15 87 60 24]
 [26 16 44 25 25]]


In [20]:
d = np.linspace(10,30,6)#it divides 10 to 30 by 6
print(d)

[10. 14. 18. 22. 26. 30.]


In [21]:
#array of evenly spaced values -> specifying the step
e = np.arange(10,32,5)#so it starts from 10 and jump by 5
print(e)

[10 15 20 25 30]


In [22]:
#convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray


Analysing a numpy array

In [23]:
c = np.random.randint(10,90,(5,5))
print(c)

[[47 24 79 22 68]
 [36 78 30 77 27]
 [76 78 59 59 22]
 [63 29 62 73 46]
 [70 24 80 11 44]]


In [24]:
# array dimension
print(c.shape)

(5, 5)


In [25]:
# number of dimensions
print(c.ndim)

2


In [26]:
# number of elements in an array
print(c.size)

25


In [27]:
# checking the data type of the values in the array
print(c.dtype)

int64



Mathematical operations on a np array

In [28]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [29]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [30]:
print(a)
print(b)

[[0 9 8]
 [5 4 3]
 [6 4 6]]
[[18 13 14]
 [13 15 18]
 [15 13 19]]


In [31]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 22 22]
 [18 19 21]
 [21 17 25]]
[[-18  -4  -6]
 [ -8 -11 -15]
 [ -9  -9 -13]]
[[  0 117 112]
 [ 65  60  54]
 [ 90  52 114]]
[[0.         0.69230769 0.57142857]
 [0.38461538 0.26666667 0.16666667]
 [0.4        0.30769231 0.31578947]]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [33]:
print(a)
print(b)

[[7 1 2]
 [5 5 4]
 [2 1 0]]
[[11 10 10]
 [13 16 12]
 [10 17 14]]


In [34]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 11 12]
 [18 21 16]
 [12 18 14]]
[[ -4  -9  -8]
 [ -8 -11  -8]
 [ -8 -16 -14]]
[[77 10 20]
 [65 80 48]
 [20 17  0]]
[[0.63636364 0.1        0.2       ]
 [0.38461538 0.3125     0.33333333]
 [0.2        0.05882353 0.        ]]


Array Manipulation

In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 9 9]
 [3 1 6]]
(2, 3)


In [36]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 3]
 [9 1]
 [9 6]]
(3, 2)


In [37]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 5 2]
 [0 5 6]]
(2, 3)


In [38]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 0]
 [5 5]
 [2 6]]
(3, 2)


In [39]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 3 0]
 [3 1 0]]
(2, 3)


In [40]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 3]
 [0 3]
 [1 0]]
(3, 2)
